name: Add images to spreadsheet
on: push

jobs:
  add-images-to-spreadsheet:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout our repository
        uses: actions/checkout@v2
      # I think technically we could omit this step
      # if we want to use the system-installed node.
      # Obviously that means less-reproduceable runs though
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          # Use the node version that is already on ubuntu-latest
          # so we don't have to download and install it.
          # See https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
          node-version: v12.16.1

      - name: Install dependencies
        run: yarn

      - name: Add new DraftImages to spreadsheet
        env:
          CURRENT_SHA: ${{ github.sha }}
          BEFORE_SHA: ${{ github.event.before }}
          SHEETS_SERVICE_ACCOUNT_EMAIL: ${{ secrets.SHEETS_SERVICE_ACCOUNT_EMAIL }}
          SHEETS_SERVICE_ACCOUNT_KEY: ${{ secrets.SHEETS_SERVICE_ACCOUNT_KEY }}
        run: node ./script.js
